### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by kevinji** [pioneers/PieCentral#116]
Since this project is open source, adding a LICENSE would be beneficial. GPLv3 and MIT are fairly common.

**Comment by nikitakit** [comment]
License file is now in the repo (this has been on my TODO for months now, it's just that I've never gotten around to it). Apache 2.0 has been the standard code license for PiE for years now, as you can see from old repos like tenshi or forseti2.

Keeping this open because we should consider adding a license blurb ([like this](https://github.com/pioneers/tenshi/blob/master/build.sh#L3)) at the top of our source files, such that the license information isn't lost as individual files get copied around.

**Comment by brandonxxlee** [comment]
@nikitakit Do you know if we should use the header from the one on the LICENSE or something like the one in tenshi. They differ by a little, so not sure which one is correct.

**Comment by kevinmasd** [comment]
Is it necessary to put the blurb everywhere? I feel that this would only be needed on code that might be used elsewhere or if parts of the code are licensed differently.

**Comment by kevinji** [comment]
Closing issue since the original issue was resolved; feel free to create a separate issue if you'd like to track adding a license blurb.
