### ISSUE TITLE
Setup presubmit check to bump runtime version

### ISSUE THREAD

**Issue by brandonxxlee** [pioneers/PieCentral#608]

**Comment by jonathan-j-lee** [comment]
I'm not sure whether we want to enforce this from the build, since version changes should be reserved for public-facing releases, not necessarily every commit to `master`. My thinking is:
1. Return to semantic versioning and decouple the year from the major version number, which should mark where backwards-incompatible changes happen.
2. Modify tags to `PROJECT/MAJOR.MINOR.PATCH-ISOTIME` so you can tell what year a release is from by just looking at the tag.

**Comment by jonathan-j-lee** [comment]
Working on a script to automatically generate tag names.

**Comment by jonathan-j-lee** [comment]
Closed by #625.
