### ISSUE TITLE
[HIBIKE] Faster serial library

### ISSUE THREAD

**Issue by baby-bell** [pioneers/PieCentral#617]
PySerial might be a bottleneck for our purpose. This needs more benchmarking, but something written in C might be better suited for this.

**Comment by jonathan-j-lee** [comment]
The relevant `pyserial` code is [`serial.serialposix`](https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py). I don't think we'd be able to get much of a speedup with C/Cython, since the underlying implementation uses bulk `os.read`s. We would also definitely lose `pyserial`'s portability.

**Comment by baby-bell** [comment]
I think this issue is unlikely to yield much speedup, so I'm closing for now.
